import { Inter } from "next/font/google";
import "./globals.css";


import { Providers } from "./Redux/providers";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Suspense } from "react";
import Loading from "./loading";

// import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stylrax_User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Suspense fallback={<Loading/>}>
        <Navbar />
          {children}
          <Footer />
        </Suspense>
        </Providers>
      </body>
    </html>
  );
}

