import { Inter } from "next/font/google";
import "./globals.css";
import fav from '@/public/favicon.ico';

import { Providers } from "./Redux/providers";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Suspense } from "react";
import "react-toastify/dist/ReactToastify.css";

import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stylrax User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" href='/favicon.ico' />
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </head>
    <body className={inter.className}>
      <Providers>
        <Navbar />
        <div className="contentWrapper">
          {children}
          <ToastContainer />
        </div>
        <Footer />
      </Providers>
    </body>
  </html>

  );
}

